# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.4
_src_path: gh:jupyterlab/extension-template
author_email: ''
author_name: Project Jupyter Contributors
data_format: string
file_extension: ''
has_binder: false
has_settings: false
kind: frontend
labextension_name: '@yunfzhou/jet_helloworld'
mimetype: ''
mimetype_name: ''
project_short_description: Minimal JupyterLab extension.
python_name: jet_helloworld
repository: https://github.com/yunfzhou/jupyterlab_extension_tutorial
test: true
viewer_name: ''

